- name: "config :: disables system swap"
  become: true
  ansible.builtin.shell: "swapoff -a"

- name: "config :: removes current swaps from the filesystem tab"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: true
    state: present

- name: "config :: ensures that br_netfilter is enabled"
  become: true
  community.general.modprobe:
    name: "br_netfilter"
    state: present

- name: "config :: sets the required networking rules"
  become: true
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: true
  loop:
    - "net.bridge.bridge-nf-call-iptables"
    - "net.ipv4.ip_forward"

- name: "config :: joins the workers to the cluster"
  become: true
  ansible.builtin.shell: |
    kubeadm join --token {{ cluster.token }} \
                 --discovery-token-unsafe-skip-ca-verification \
                 --cri-socket=/var/run/containerd/containerd.sock \
                 {{ hostvars[groups['masters'][0]].ansible_host }}:6443
