- name: "install :: updates package lists"
  become: true
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: "install :: upgrades package lists"
  become: true
  ansible.builtin.apt:
    upgrade: full
    force_apt_get: true

- name: "install :: installs the ContainerD packages"
  become: true
  ansible.builtin.apt:
    pkg:
      - containerd
    force_apt_get: true
